### ISSUE TITLE
Some In-World transmutation EMC values

### ISSUE THREAD

**Issue by cherubael1010** [ChosenArchitect/Project-Architect-2#104]
-> Add EMC values to Sky Steel Ingots (256 EMC) and Redstone Crystal (990 EMC) to reduce item lag on servers/make life easy. If you could also add EMC to Crystalized Menril Chunks and Crystalized Chorus Chunks, that would be swell

**Describe the solution you'd like**
-> Addition of EMC to listed items

**Describe alternatives you've considered**
-> N/A

**Mod Sugestions**
-> GregTech CE (mostly joking lol)

**Additional context**
-> N/A

**Comment by IRicTheCoder** [comment]
Instead of adding EMC value to the In-World recipes, an alternative recipe was added into the Dissolution Chamber from Industrial Foregoing that should help with lag. The Chunks have not been given EMC value for the time being. Since the title suggests this was mainly related to lag and the In-World transmutation recipes, will close this as done.
