### ISSUE TITLE
Suggestion: Upload source to github repo

### ISSUE THREAD

**Issue by VendoAU** [ChosenArchitect/Project-Architect-2#122]
I think it would be a good idea to upload the modpack files to github so people can then create pull requests for bug fixes or new features

Only the config files should be needed
Here's an example:
https://github.com/AllTheMods/ATM-9

**Comment by ChosenArchitect** [comment]
If I was well versed enough with Get then I would do that but I just don't have the time right now to learn this (maybe one day!)

**Comment by IRicTheCoder** [comment]
This late down the line of the modpack development adding those things here would not give that much benefit, and as Chosen said above it also requires some more understanding of how github works, maybe in a future pack. Closing this as not planned since that makes more sense.

Thanks for your feedback!
