### ISSUE TITLE
Structures spawning in a Dimension with a None dimlet

### ISSUE THREAD

**Issue by thransk** [ChosenArchitect/Project-Architect-2#137]
**Describe the bug**
-> Dimensions with a Structure Dimlet Key:None and at least one overworld biome still spawn with Trial Chambers and other structures.

**To Reproduce**
1.  Create a dimension with Structure Dimlet, Key: none and at least one overworld biome
2.  Enter the dimension
3.  The dimension will contain Trial Chambers, possibly more structures depending on biomes, such a jungle mineshafts

**Expected behavior**
-> No structures should be spwaning

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.3.2
**Java Version**
->
**Modpack Launcher Used**
->ATLauncher
**Ram Allocated**
->8192

**Additional context**
->

**Comment by aphroidite** [comment]
Same for me, using both curseforge direct launch and the oficial launcher.
The biggest issue is that trial spawners and vaults can't be removed on survival.

**Comment by IRicTheCoder** [comment]
Unfortunately controlling the structures that go into the None Dimlet and removing all of them isn't that easy, I have been looking into it. So for the time being we made it so that it is possible to break the content of the trials entirely. As long as spawners and vaults have been used and are inactive they can be removed, they drop with silk touch.

This should help for now!

**Comment by IRicTheCoder** [comment]
The Trials should no longer appear on the dimensions, we added the configuration for that but due to some issues the mod itself has it might not be enough to remove it fully, they should at least be less frequent. Closing this as solved for now.
