### ISSUE TITLE
[SUGGESTION] Drygmy loot table / in world crafting /More creative items

### ISSUE THREAD

**Issue by ryennce** [ChosenArchitect/Project-Architect-2#164]
**Is your feature request related to a problem? Please describe.**
->

First problem:

The problem is farming Nether Stars and Dragon Hearts (from Draconic Evolution) in the world, with the latter being impossible. Although there is an Ender Dragon spawner, the mob itself doesn't drop anything.

The Nether Star issue is related to in-world mob spawning, which can cause lag and is often banned on some servers. On a multiplayer server, farming those mobs in the world can be quite problematic, and you need lots of Nether Stars for Powah and other mods.

Second problem:
Also, other issue with in world lag, please ad EMC to the skystone ingot and Redstone Crystal for less in world item crafting

Third:
There should be more creative items, for refference there is the energy cell from the AE2 but there isnt the creative controller from refined storage

**Describe the solution you'd like**
-> Without the addition of new mods, it would be possible to add Nether Stars to the Wither loot table and Dragon Hearts to the Ender Dragon within containment jars for the Drygmy mob farm.

**Describe alternatives you've considered**
->
For the Ender Dragon, one alternative could be adding EMC to the Dragon Heart or any of its crafted items. However, since the modpack is focused on farming resources for EMC, making only the Dragon Heart EMCble would be beneficial. This way, you can automate the crafting of other items using Refined Storage or AE2.

As for Nether Stars, I haven't found another effective method of farming them besides killing the Wither (either via a mob spawner or the Wither Builder from the Industrial Foregoing mod). Making them EMCble might make it too easy.

Other mobs that could have the same treatment: Wilden chimera (For the tribute), common/rare/legendary blob (They dont drop theyr respective items in the drygmy mob farm).

---ALSO: Consider removing the Wither from the blacklist for the Mob Swab since its spawn egg can be obtained through the Capturing enchantment.

**Mod Sugestions**
-> 
- Hostile Neural Networks (Tbh, the only other mob i could think of that would make a nice lag reduction)
- Occultism (For an extra storage option and more ways of ore processing)
- Ars Ocultas (So that the ore process from the occultism mod can be automated in containment jars)
- Twilight forest (For new building blocks and adventure)
- More structures mods? I know, but i finished the pack and one thing i missed in the beggining is that i couldnt find a nice structure to steal and call it home.

**Additional context**
->
I don't know how to add items to the Drygmy loot table; I only know it's possible because I've seen it done in the All the Mods 9 modpack.

About the Creative spell book, it only has all the glyphs, it still drains your mana, is almost useless. I dont know if anyone feels the same way but making the glyphs is quite fun, i dont know if its a setting or if its supposed to be that way, but having infinite mana was kinda what i was expecting.

-more magic mods ? Maybe iron spells and stuff. Modular golems, maybe.
Some other creature mods could be good too, i also missed the lack of magical creatures in the pack (like dragons, unicorns, a giant forger with an hammer in the nether that can smash you, a giant obelisk in the end that can kill you, you know that sorta stuff)

The progression of the modpack seems to be quite linear, maybe adding few more ways to making the items 
Tbh, i not a fan of create, having another block to craft the final star would be nice.

**Comment by IRicTheCoder** [comment]
I understand some of your points, so I will address what I can:

- Farming Dragon Hearts is easy, it is hard to automated but it is possible, specially if you are playing in single player. However, it is mostly needed for the awakening draconium blocks, which can be turned to ingots and turned into dust which has EMC. So killing the dragon a couple of times should be enough.

- I find it hard for a modpack that has spawners as an obtainable item (normal spawners not even modded ones), to have banned In-World spawning, limited sure, banned seems more illogical. Also the reason why somethings might not drop in a Drygmy farm is because it might not count as a player kill, but I am unsure about that.

- If you look at the change log of version 3.4 and 3.5 or the #154 which was added on 3.4, there are alternative recipes to the redstone crystal and sky steel ingot, they are slightly more expensive for balancing. EMC won't be added to them at this time. Also sky steel ingots are available through Fluix Researcher Villagers, which can be automated.

- The creative controller for refined storage might have been an oversight, however, you have creative energy cells from Mekanism which you can use to power the refined storage.

- We will discuss the possibility of adding it to the drygmy loot tables.

- Blobs are meant to be farmed as is, hence why they also don't have a spawn egg, they are meant to be farmed inside the dimensions, and for now will remain as such.

- The Wilden is the same situation as the Wither and others, in a modpack that has it, not allowing in-world spawning is weird. For now not much can be done on this, we will see.

- You have some interesting suggestions in terms of mods, however things like Twilight are most likely not gonna be added, as the pack is reaching a more stable, sort of structured form.

In general we will see what from here might or not be considered and added.

**Comment by ryennce** [comment]
> I understand some of your points, so I will address what I can:
> 
> * Farming Dragon Hearts is easy, it is hard to automated but it is possible, specially if you are playing in single player. However, it is mostly needed for the awakening draconium blocks, which can be turned to ingots and turned into dust which has EMC. So killing the dragon a couple of times should be enough.
> * I find it hard for a modpack that has spawners as an obtainable item (normal spawners not even modded ones), to have banned In-World spawning, limited sure, banned seems more illogical. Also the reason why somethings might not drop in a Drygmy farm is because it might not count as a player kill, but I am unsure about that.
> * If you look at the change log of version 3.4 and 3.5 or the [Bunch of Fixes + Extras #154](https://github.com/ChosenArchitect/Project-Architect-2/issues/154) which was added on 3.4, there are alternative recipes to the redstone crystal and sky steel ingot, they are slightly more expensive for balancing. EMC won't be added to them at this time. Also sky steel ingots are available through Fluix Researcher Villagers, which can be automated.
> * The creative controller for refined storage might have been an oversight, however, you have creative energy cells from Mekanism which you can use to power the refined storage.
> * We will discuss the possibility of adding it to the drygmy loot tables.
> * Blobs are meant to be farmed as is, hence why they also don't have a spawn egg, they are meant to be farmed inside the dimensions, and for now will remain as such.
> * The Wilden is the same situation as the Wither and others, in a modpack that has it, not allowing in-world spawning is weird. For now not much can be done on this, we will see.
> * You have some interesting suggestions in terms of mods, however things like Twilight are most likely not gonna be added, as the pack is reaching a more stable, sort of structured form.
> 
> In general we will see what from here might or not be considered and added.

Thanks for the fast feedback, apologies for not seeing the update. And thanks for the consideration.
As for the automation of the wilden and wither i only thought about it after but here is a final suggestion to close the post:

Since industrial foregoing is in the pack theres the mob imprisonment tool, however the wither and Wilden Chimera cant be caught by it. That being another way of farming it. 

![2024-08-22_18 22 58](https://github.com/user-attachments/assets/95ac0333-1b03-484e-8651-15e079cb19a7)


Again, thanks for reading and considering the suggestion.

**Comment by IRicTheCoder** [comment]
Some of the suggestions here were added in some capacity, in version 4.0 there should be some means to farm some of the things mentioned. The rest was considered but for now will not be added. Thanks for the feedback, closing this issue.
