### ISSUE TITLE
Client crashes and unable to rejoin wearing Ars elemental armor

### ISSUE THREAD

**Issue by Malicante** [ChosenArchitect/Project-Architect-2#205]
Ars Elemental is having a clash with Deeper and Darker and Apotheosis when you take damage in Geomancer armor that's been augmented to Mythic (at the least, the server I play on isn't mine, so no creative testing.) Attached is the error code.

**To Reproduce**
1.  Augment Ars Elemental armor (In this case Geomancer)
2. Equip said armor
3. Get hit
4. Client crashes from server with an "Unable to connect you to the hub" message and cannot rejoin until client player is warped some distance away.
5. chunks of the world remain usable and uncorrupted, however the equipped player taking damage again causes a repeat of step 4.

**Expected behavior**
-> I expected to take damage and murderbrawl some creatures.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.6
**Java Version**
->
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 16Gb

**Additional context**
->
[message.txt](https://github.com/user-attachments/files/16830480/message.txt)

**Comment by Micaxs** [comment]
Just remove ars elemental mod and it resolves the issue.

**Comment by Virii333** [comment]
Can we just remove it from the server side without the client sides making changes or does everyone have to make the adjustment.  

For reference we did some testing, It has to do with the armor and I think the durability of it.  If I punch someone in armor, the server would crash.  but if he would walk into a cactus the client would crash not the server.  I'm not smart enough to go past that, but since we don't have a hotfix does anyone know if I can remove the mod from the server and solve the issue?

**Comment by ChosenArchitect** [comment]
Unfortunately the mod is tied into the progression of the mod pack. I would recommend potentially not wearing that armor. I'm still waiting for the mod to update.

**Comment by IRicTheCoder** [comment]
There have been some updates up to 4.3 that could help with this, so it is possible it no longer happens, as I have not been able to replicate it. Will close the issue as solved, but if it happens again just reopen this one, or message here.
