### ISSUE TITLE
I think that the snad unbalances the early game.

### ISSUE THREAD

**Issue by SiriosDev** [ChosenArchitect/Project-Architect-2#215]
**Is your feature request related to a problem? Please describe.**
I think the snad is too op for the stage it is in, especially combined with the bamboo it gives quick access to a very fast farm of mana, emc and energy

**Describe the solution you'd like**
Pairing a clock to the snad and in turn using this system with some bamboo allows firstly to packet 3x3 the bamboo having an infinite source of fuel (and consequently energy) at the same time the excess of leaves goes to generate a lot of emc and lastly the growth of the plant triggers the vitalic sourcelink allowing fulling a jar in not even 2 minutes (only considering 4 snad)

**Describe alternatives you've considered**
I don't think this is necessarily a bad thing, but its being immediately accessible imho, easily unbalances the pack, consequently I think it would be a better choice to move the snad ahead in “progression” by creating a more difficult craft or at least that is not just two sand (and some redstone for clock) 

**Mod Sugestions**
N/A

**Additional context**
N/A

**Comment by LuciusV** [comment]
My opinion:
If you don't like it, don't use it
It's already grindy enough for me

**Comment by IRicTheCoder** [comment]
This is not a big issue, the bamboo can also be easily automated in another ways and give you a lot of EMC too. I would add these points:

- You can craft an Infinite Fuel from ProjectExpansion relatively early which means infinite fuel at the cost of 128 EMC per second which is nothing
- I think you mean the Agro Sourcelink since the Vitalic one is for mobs, which in a mob farm with dreadful dirt or a spawner can fill 4 jars in under 30 seconds
- There are a lot of very early options, that give you far more EMC, but still are far from comparing to the Archi-blocks or mid/end-game farms. Also a diamond block farm is relatively easy to do even early game and gives you billions of EMC.

This being said, for now we don't consider this to be an issue, as such I will close this as not planned, since we do not plan on changing this at the moment.
