### ISSUE TITLE
Blazing Rods wont work in auto crafting recipes 

### ISSUE THREAD

**Issue by SinFLUXX** [ChosenArchitect/Project-Architect-2#223]
**Describe the bug**
->Setting a crafting recipe for the blazing agitator to make blazing rods. The craft will not complete when the blazing rods are finished. 

Using blazing rods in auto craft recipes will only work when using a specific rod. It will not use anything that doesnt match the NBT data of said specific rod.

**To Reproduce**
1. set crafting pattern to make blazing rod
2. wait until craft finishes
3. auto craft will not complete
4. 

**Expected behavior**
-> I expect to be able to use the rods in the crafting recipes.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![screen shot bug 1](https://github.com/user-attachments/assets/f4e5b529-8d2c-4128-b7f9-a51b14de9686)
![screen shot bug 2](https://github.com/user-attachments/assets/47244773-4c5a-4f4e-8b54-167cff5f95a0)

**Modpack version**
->Project Architect 2 - 2.3
**Java Version**
->1.20.1
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->all of it

**Additional context**
->

**Comment by IRicTheCoder** [comment]
This is intended behavior, you need to filter it so it only takes a fully charged blazing rod, or try to take it the moment it enters the machine, Applied Energistics does not allow for ignore NBTs in processing patterns. Alternatively you could build a Refined Storage system for that specific purpose as that does allow for the NBT to be ignored.

On another note, you might experience other issues since you are still in version 2.3, you should consider updating.

And you do not need to allocate more than 10GB RAM for this pack unless you are using shaders, giving it all you have available will not only cause issues with the Operating System, but can also lower your RAMs lifetime drastically due to forced memory manipulation.
