### ISSUE TITLE
Dragons "healing beam" stays after removing the end crystal

### ISSUE THREAD

**Issue by Ixzat** [ChosenArchitect/Project-Architect-2#224]
**Describe the bug**
Went to the end, got to kill the dragon. Got rid of all the end crystal on the towers, however one beam is still active and i cannot get rid of the four end crystals on the ground. This makes it so i can not respawn the dragon.
->

**To Reproduce**
1. Go to the end
2. Get rid of the End crystals on the towers

**Expected behavior**
Be able to respawn the dragon
->

**Screenshots**
![2024-09-12_08 19 53](https://github.com/user-attachments/assets/0d50e638-6c8c-4015-808d-f775b5f77330)
![2024-09-12_08 20 17](https://github.com/user-attachments/assets/f62e5f95-040b-444e-9e1c-32464832f615)

**Modpack version**
3.6
->
**Java Version**
17.0.8
->
**Modpack Launcher Used**
Curseforge
->
**Ram Allocated**
8GB
->

**Additional context**
I tried removing the DIM1 folder to regenerate the End in my world, but when i rejoined the end via the portal in the stronghold and went to 0,0, all i got was the modified towers without the middle structure and no dragon spawning.
->

**Comment by IRicTheCoder** [comment]
Seems like a peculiar problem you have here, my advice would be to try and place one block where the crystal used to be, because it might have been broken only visually, and bugged. Alternatively you can try this `/kill @e[type=minecraft:end_crystal]` which should kill all crystals.

If that doesn't work we can think about next steps, let me know.

**Comment by Ixzat** [comment]
Placing a block did not work, however running the command did remove the crystals, the dragon could be respawned and everything seems to be fine now.

Thank you!
