### ISSUE TITLE
Some mods that should be added

### ISSUE THREAD

**Issue by Gottaloveeggs** [ChosenArchitect/Project-Architect-2#227]
**Is your feature request related to a problem? Please describe.**
->no, except one

**Describe the solution you'd like**
->adding some performance mods to increase performance (note: I've not benchmarked b/a, just guessing it does), Fps reducer for AFKing(temporal pouch, emc, and anything that requires waiting) and most importantly, replacing  [Light Overlay](https://www.curseforge.com/minecraft/mc-mods/light-overlay) with [More Overlays Updated](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated) because it has JEI searching in inventories (makes finding thing much easier)
Side note: add emc values to Chisel Chipped Integration, FramedBlocks, and other decoration blocks

**Describe alternatives you've considered**
->just not adding some of them

**Mod Suggestions**
(Replace [Light Overlay](https://www.curseforge.com/minecraft/mc-mods/light-overlay) with)(most important) 
->[More Overlays Updated](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated)
(performance mods) ([some others you can think about](https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance120.md#forge-120x))
->[Better chunk loading[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
->[Better Fps - Render Distance[Forge]](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
->[Bocchium](https://www.curseforge.com/minecraft/mc-mods/bocchium)
->[Client Crafting](https://www.curseforge.com/minecraft/mc-mods/client-crafting)
->[Entity Culling Fabric/Forge](https://www.curseforge.com/minecraft/mc-mods/entityculling)
->[Radium Reforged](https://www.curseforge.com/minecraft/mc-mods/radium-reforged)
->[Recipe Essentials ](https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric)
(for AFKing)
->[FPS Reducer](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)

**Additional context**
->

**Comment by IRicTheCoder** [comment]
Let me give some input/feedback on this:

- **`Better chunk loading`** can cause issues on some situations with loaded chunks and chunk claims. It can also break, not due to incompatibilities per say, but due to some variables aligning while playing. Testing this is complex and might not be worth the investment this late in pack development.
- **`Bocchium`** doesn't increase that much performance unless you are always doing stuff very close to Bedrock.
- **`Client Crafting`** can have issues with some of the KubeJS modified recipes, this shouldn't be a problem per say, but it will still cause some visual artifacts before syncing back with the server.
- **`Recipe Essentials`** is incompatible with `Not Enough Recipe Book` and `FastSuite` both installed in the pack already.

As for the rest, we will see.

**Comment by Gottaloveeggs** [comment]
I see, well those weren't super important anyway, more overley updated is the only really important suggestion

**Comment by IRicTheCoder** [comment]
The `More Overlay Updated` mod has been added to version 4.7 to replace the `Light Overlay`, the rest of the mods won't be added as they do not realistically improve the pack that much and most can cause issues with other mods already present.

As for the FPS Reducer, feel free to add it on your own, as it should work. Closing the issue as solved.
