### ISSUE TITLE
Fluix Crystal excess EMC

### ISSUE THREAD

**Issue by MadisonBarks** [ChosenArchitect/Project-Architect-2#241]
**Describe the bug**
_A clear and concise description of what the bug is._
The Fluix Crystal can be exploited as a sort of EMC farm. Charged Certus (256 EMC) + Nether Quartz (256 EMC) + Redstone Dust (64 EMC) is a total of 576 EMC, and produces two Fluix Crystals (413 EMC each), creating an excess of 250 EMC per pair of Fluix Crystals. 

**Expected behavior**
_A clear and concise description of what you expected to happen._
Fluix Crystal EMC value of 288

**Modpack version**
4.2 (also applicable in 3.6)
**Java Version**
17.0.12 (Eclipse Temurin)
**Modpack Launcher Used**
Prism
**Ram Allocated**
8G or so

**Comment by IRicTheCoder** [comment]
There are a lot more ways to do duping of EMC, actually the progression of the pack is designed like that. Archimeat costs 20M to produce gives you 50M, its how you farm EMC.

This is not an issue, even if not intentional. You have a lot more profitable dupes before Archimeat, or even super farms.

Closing this as not an issue, but thank you for the report.
