### ISSUE TITLE
2 Mods I want added

### ISSUE THREAD

**Issue by Charizard748** [ChosenArchitect/Project-Architect-2#245]
**Is your feature request related to a problem? Please describe.**
->Draconic Infusion crafting is hard to automate without a weird setup(possibly lag inducing as it uses Xnet).

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
->Add PakagedAuto and PackagedDraconic.

**Additional context**
->PackagedAuto packager packs multiple items into 1 item then uses the Unpacker to send into a crafting block(ie AE2 Molecular Assembler). With PackagedDraconic, it adds blocks that are basically the same as the normal Draconic Infusing blocks, but it works it the Unpacker to auto craft, also if the center block is connected to AE, it will automatically export into AE storage and receive power.

**Comment by IRicTheCoder** [comment]
Using things as modular routers, Super Factory Manager (its very lag free when well done), and others it becomes trivial to automate the Infusion Crafting.

However, we can discuss the possibility of adding such a mod, but I do not think it is likely to be added.

**Comment by IRicTheCoder** [comment]
Just spoke to Chosen and this will not be added, at this point in the pack development we are avoiding adding more mods, since we consider the pack to be basically done only needing bug fixes and such.

If it was the beginning of the pack development it would make a lot more sense, but it is simple to add if you which to do so on your own install.

Thank you for the suggestion!
