### ISSUE TITLE
There should be a crafting recipe for the Draconic Evolution Information Tablet

### ISSUE THREAD

**Issue by 12Ooats** [ChosenArchitect/Project-Architect-2#264]
**Is your feature request related to a problem? Please describe.**
-> There doesn't seem to be a way to craft the Information Tablet in game. 

**Describe the solution you'd like**
-> The recipe I have always seen is 8 stone around 1 Draconium Dust.

**Describe alternatives you've considered**
-> Please add a recipe for the tablet?

**Mod Suggestions**
-> Draconic Evolution

**Additional context**
->
![image](https://github.com/user-attachments/assets/be9aed65-9a27-4e33-99db-400c19175ae8)
![image](https://github.com/user-attachments/assets/c091f363-6fdc-4e94-b707-b9294ac83ce7)

**Comment by IRicTheCoder** [comment]
The Tablet is a legacy item in Draconic Evolution, it simply wasn't removed, but the recipe for it was removed by the **mod dev** themselves. The tablet requires a mod to work that has not been updated since 1.16, so it makes it impossible to function in newer versions.

This being said, we removed the tablet from JEI in newer version of Project Architect 2 so it shouldn't be appearing at all.

We will **not** be adding any recipes for it, since the mod itself intends for the item to not be used and it will most likely be removed or replaced on an upcoming update. Even if we did add a recipe, the item cannot be used for the reasons mentioned above.

Closing this issue as not planned/won't fix since this is not a real issue from the pack's standing point.
