### ISSUE TITLE
Mod Suggestion: Create: Steam 'n' Rails

### ISSUE THREAD

**Issue by Itzbionicz** [ChosenArchitect/Project-Architect-2#41]
Hello. 

As a someone who likes to use the Create mod for building, decorating, and automation, the mod I'm suggesting is Create: Steam 'n' Rails. Being able to use some of the features in Steam 'n' Rails are really fun to use for making train networks. I know we have way better ways of transporting items over long distances like EnderStorage's Ender Chests, but this would still be fun for the people who wanna transport items over long distances in a fun way. If you don't wanna add this, that's alright. 

Thank you,
Itzbionicz

**Comment by IRicTheCoder** [comment]
Create: Steam 'n' Rails is a nice mod but it would require some tweaks to fit into some parts of the pack, it also can cause more TPS issues and lag on servers if used too much, as most train and minecart related things would. For now this won't me added, since as of version 4.0 we will avoid adding more mods.

Thank you for your feedback, closing this issue as not planned.
